package io.miragon.training.adapter.outbound.engine;

import io.miragon.training.adapter.process.SendWelcomeKitProcessApi;
import io.miragon.training.application.port.outbound.WelcomeKitProcess;
import org.operaton.rest.client.api.ProcessDefinitionApi;
import org.operaton.rest.client.model.StartProcessInstanceDto;
import org.operaton.rest.client.model.VariableValueDto;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Component;

import java.util.Map;

/**
 * Drives the shared, remote Operaton engine over its REST API to start the owned {@code sendWelcomeKit}
 * process (Direction 2: worker -> engine). The REST call goes through the <strong>autogenerated,
 * typed</strong> client ({@link ProcessDefinitionApi} from {@code operaton-engine-client}) rather than
 * hand-built REST, so URIs and the typed-variable payload ({@code {value, type}}) are compile-checked.
 * The process id comes from the typed process API this service generates from its own BPMN.
 */
@Component
public class RemoteWelcomeKitProcessAdapter implements WelcomeKitProcess {

    private static final Logger log = LoggerFactory.getLogger(RemoteWelcomeKitProcessAdapter.class);

    private final ProcessDefinitionApi processDefinitionApi;

    public RemoteWelcomeKitProcessAdapter(ProcessDefinitionApi processDefinitionApi) {
        this.processDefinitionApi = processDefinitionApi;
    }

    @Override
    public void startWelcomeKit(String memberName) {
        StartProcessInstanceDto request = new StartProcessInstanceDto()
                .variables(Map.of("name", new VariableValueDto().value(memberName).type("String")));

        processDefinitionApi.startProcessInstanceByKey(SendWelcomeKitProcessApi.PROCESS_ID.getValue(), request);
        log.info("Started a remote sendWelcomeKit instance for member {}", memberName);
    }
}
