spring:
  datasource:
    url: jdbc:h2:mem:operaton-exercise-task-1;DB_CLOSE_DELAY=-1;INIT=CREATE SCHEMA IF NOT EXISTS exercise
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

operaton:
  bpm:
    database:
      type: h2
