server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/operaton-training?currentSchema=exercise
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: exercise

operaton:
  bpm:
    admin-user:
      id: admin
      password: admin
    database:
      type: postgres
      schema-update: true
