// Generated by bpmn-to-code
package io.miragon.training.adapter.process;

import io.miragon.bpmn.runtime.SignalName;
import java.util.List;

/**
 * BPMN signal names broadcast and caught by signal events.
 */
public final class Signals {
  public static final SignalName MEMBER_ACTIVATED = new SignalName("Signal_MemberActivated");

  private Signals() {
  }

  public static List<SignalName> all() {
    return List.of(
        MEMBER_ACTIVATED);
  }
}
