// Generated by bpmn-to-code
package io.miragon.training.adapter.process;

import io.miragon.bpmn.runtime.AbstractFlowNode;
import io.miragon.bpmn.runtime.BpmnElementType;
import io.miragon.bpmn.runtime.BpmnEngine;
import io.miragon.bpmn.runtime.BpmnEventType;
import io.miragon.bpmn.runtime.ElementId;
import io.miragon.bpmn.runtime.Event;
import io.miragon.bpmn.runtime.FlowNode;
import io.miragon.bpmn.runtime.HasSuccessors;
import io.miragon.bpmn.runtime.ProcessId;
import io.miragon.bpmn.runtime.SequenceFlows;
import java.util.List;

public final class HandleRejectionProcessApi {
  public static final ProcessId PROCESS_ID = new ProcessId("handleRejection");

  public static final BpmnEngine PROCESS_ENGINE = BpmnEngine.CAMUNDA_7;

  private HandleRejectionProcessApi() {
  }

  /**
   * Typed navigation over the process flow: one nested class per BPMN element.
   */
  public static final class FlowNodes {
    private FlowNodes() {
    }

    public static EndEventAcceptRejection endEventAcceptRejection() {
      return EndEventAcceptRejection.INSTANCE;
    }

    public static EndEventTriedToReacquire endEventTriedToReacquire() {
      return EndEventTriedToReacquire.INSTANCE;
    }

    public static GatewayHighValue gatewayHighValue() {
      return GatewayHighValue.INSTANCE;
    }

    public static ServiceTaskCategorizeApplicant serviceTaskCategorizeApplicant() {
      return ServiceTaskCategorizeApplicant.INSTANCE;
    }

    public static StartEventConfirmationRejected startEventConfirmationRejected() {
      return StartEventConfirmationRejected.INSTANCE;
    }

    public static UserTaskWriteRegretMail userTaskWriteRegretMail() {
      return UserTaskWriteRegretMail.INSTANCE;
    }

    public static List<FlowNode> all() {
      return List.of(
          EndEventAcceptRejection.INSTANCE,
          EndEventTriedToReacquire.INSTANCE,
          GatewayHighValue.INSTANCE,
          ServiceTaskCategorizeApplicant.INSTANCE,
          StartEventConfirmationRejected.INSTANCE,
          UserTaskWriteRegretMail.INSTANCE);
    }

    public static final class EndEventAcceptRejection extends AbstractFlowNode implements Event {
      public static final String ELEMENT_ID = "endEvent_acceptRejection";

      public static final EndEventAcceptRejection INSTANCE = new EndEventAcceptRejection();

      private EndEventAcceptRejection() {
        super(new ElementId(ELEMENT_ID), BpmnElementType.END_EVENT, "Accept rejection");
      }

      @Override
      public BpmnEventType getEventType() {
        return BpmnEventType.NONE;
      }
    }

    public static final class EndEventTriedToReacquire extends AbstractFlowNode implements Event {
      public static final String ELEMENT_ID = "endEvent_triedToReacquire";

      public static final EndEventTriedToReacquire INSTANCE = new EndEventTriedToReacquire();

      private EndEventTriedToReacquire() {
        super(new ElementId(ELEMENT_ID), BpmnElementType.END_EVENT, "Tried to reaquire applicant");
      }

      @Override
      public BpmnEventType getEventType() {
        return BpmnEventType.NONE;
      }
    }

    public static final class GatewayHighValue extends AbstractFlowNode implements HasSuccessors<GatewayHighValue.Next> {
      public static final String ELEMENT_ID = "gateway_highValue";

      public static final GatewayHighValue INSTANCE = new GatewayHighValue();

      private GatewayHighValue() {
        super(new ElementId(ELEMENT_ID), BpmnElementType.EXCLUSIVE_GATEWAY, "High value?");
      }

      @Override
      public Next getNext() {
        return new Next();
      }

      public static final class Next {
        public SequenceFlows<EndEventAcceptRejection> endEventAcceptRejection() {
          return SequenceFlows.single(new ElementId("Flow_1imjd1v"), null, null, true, EndEventAcceptRejection.INSTANCE);
        }

        public SequenceFlows<UserTaskWriteRegretMail> userTaskWriteRegretMail() {
          return SequenceFlows.single(new ElementId("Flow_07y997b"), null, "${isHighValue}", false, UserTaskWriteRegretMail.INSTANCE);
        }
      }
    }

    public static final class ServiceTaskCategorizeApplicant extends AbstractFlowNode implements HasSuccessors<ServiceTaskCategorizeApplicant.Next> {
      public static final String ELEMENT_ID = "serviceTask_categorizeApplicant";

      public static final ServiceTaskCategorizeApplicant INSTANCE = new ServiceTaskCategorizeApplicant();

      private ServiceTaskCategorizeApplicant() {
        super(new ElementId(ELEMENT_ID), BpmnElementType.BUSINESS_RULE_TASK, "Categorize applicant");
      }

      @Override
      public Next getNext() {
        return new Next();
      }

      public static final class Next {
        public SequenceFlows<GatewayHighValue> gatewayHighValue() {
          return SequenceFlows.single(new ElementId("Flow_0gvf8zj"), GatewayHighValue.INSTANCE);
        }
      }
    }

    public static final class StartEventConfirmationRejected extends AbstractFlowNode implements HasSuccessors<StartEventConfirmationRejected.Next>, Event {
      public static final String ELEMENT_ID = "startEvent_confirmationRejected";

      public static final StartEventConfirmationRejected INSTANCE = new StartEventConfirmationRejected();

      private StartEventConfirmationRejected() {
        super(new ElementId(ELEMENT_ID), BpmnElementType.START_EVENT, "Confirmation rejected");
      }

      @Override
      public BpmnEventType getEventType() {
        return BpmnEventType.NONE;
      }

      @Override
      public Next getNext() {
        return new Next();
      }

      public static final class Next {
        public SequenceFlows<ServiceTaskCategorizeApplicant> serviceTaskCategorizeApplicant() {
          return SequenceFlows.single(new ElementId("Flow_0vqwqsj"), ServiceTaskCategorizeApplicant.INSTANCE);
        }
      }
    }

    public static final class UserTaskWriteRegretMail extends AbstractFlowNode implements HasSuccessors<UserTaskWriteRegretMail.Next> {
      public static final String ELEMENT_ID = "userTask_writeRegretMail";

      public static final UserTaskWriteRegretMail INSTANCE = new UserTaskWriteRegretMail();

      private UserTaskWriteRegretMail() {
        super(new ElementId(ELEMENT_ID), BpmnElementType.USER_TASK, "Write an email expressing regret");
      }

      @Override
      public Next getNext() {
        return new Next();
      }

      public static final class Next {
        public SequenceFlows<EndEventTriedToReacquire> endEventTriedToReacquire() {
          return SequenceFlows.single(new ElementId("Flow_1ufk6o2"), EndEventTriedToReacquire.INSTANCE);
        }
      }
    }
  }
}
