// Generated by bpmn-to-code
package io.miragon.training.adapter.process;

import io.miragon.bpmn.runtime.AbstractFlowNode;
import io.miragon.bpmn.runtime.AssociatedCompensationHandler;
import io.miragon.bpmn.runtime.AttachedBoundaryEvent;
import io.miragon.bpmn.runtime.BoundaryEvent;
import io.miragon.bpmn.runtime.BpmnElementType;
import io.miragon.bpmn.runtime.BpmnEngine;
import io.miragon.bpmn.runtime.BpmnEventType;
import io.miragon.bpmn.runtime.BpmnTimer;
import io.miragon.bpmn.runtime.CallActivity;
import io.miragon.bpmn.runtime.CompensationThrowEvent;
import io.miragon.bpmn.runtime.ElementId;
import io.miragon.bpmn.runtime.Event;
import io.miragon.bpmn.runtime.FlowNode;
import io.miragon.bpmn.runtime.FlowScope;
import io.miragon.bpmn.runtime.HasJobType;
import io.miragon.bpmn.runtime.HasMessage;
import io.miragon.bpmn.runtime.HasSuccessors;
import io.miragon.bpmn.runtime.HasVariables;
import io.miragon.bpmn.runtime.InputOutputMapping;
import io.miragon.bpmn.runtime.MessageName;
import io.miragon.bpmn.runtime.ProcessId;
import io.miragon.bpmn.runtime.SequenceFlows;
import io.miragon.bpmn.runtime.TimerEvent;
import io.miragon.bpmn.runtime.TimerType;
import io.miragon.bpmn.runtime.VariableDefinitions;
import io.miragon.bpmn.runtime.VariableName;
import java.util.List;

public final class SubscribeNewsletterProcessApi {
  public static final ProcessId PROCESS_ID = new ProcessId("subscribeNewsletter");

  public static final BpmnEngine PROCESS_ENGINE = BpmnEngine.CAMUNDA_7;

  private SubscribeNewsletterProcessApi() {
  }

  /**
   * Typed navigation over the process flow: one nested class per BPMN element.
   */
  public static final class FlowNodes {
    private FlowNodes() {
    }

    public static BoundaryCompensateClaim boundaryCompensateClaim() {
      return BoundaryCompensateClaim.INSTANCE;
    }

    public static CallActivityHandleRejection callActivityHandleRejection() {
      return CallActivityHandleRejection.INSTANCE;
    }

    public static EndEventMailSentAgain endEventMailSentAgain() {
      return EndEventMailSentAgain.INSTANCE;
    }

    public static EndEventMembershipActivated endEventMembershipActivated() {
      return EndEventMembershipActivated.INSTANCE;
    }

    public static EndEventMembershipConfirmed endEventMembershipConfirmed() {
      return EndEventMembershipConfirmed.INSTANCE;
    }

    public static EndEventMembershipDeclined endEventMembershipDeclined() {
      return EndEventMembershipDeclined.INSTANCE;
    }

    public static EndEventMembershipRejected endEventMembershipRejected() {
      return EndEventMembershipRejected.INSTANCE;
    }

    public static EventConfirmationRejected eventConfirmationRejected() {
      return EventConfirmationRejected.INSTANCE;
    }

    public static GatewayHasEmptySpots gatewayHasEmptySpots() {
      return GatewayHasEmptySpots.INSTANCE;
    }

    public static GatewayNotifyFork gatewayNotifyFork() {
      return GatewayNotifyFork.INSTANCE;
    }

    public static GatewayNotifyJoin gatewayNotifyJoin() {
      return GatewayNotifyJoin.INSTANCE;
    }

    public static ServiceTaskClaimMembership serviceTaskClaimMembership() {
      return ServiceTaskClaimMembership.INSTANCE;
    }

    public static ServiceTaskNotifyCommunity serviceTaskNotifyCommunity() {
      return ServiceTaskNotifyCommunity.INSTANCE;
    }

    public static ServiceTaskReSendConfirmationMail serviceTaskReSendConfirmationMail() {
      return ServiceTaskReSendConfirmationMail.INSTANCE;
    }

    public static ServiceTaskRevokeClaim serviceTaskRevokeClaim() {
      return ServiceTaskRevokeClaim.INSTANCE;
    }

    public static ServiceTaskSendConfirmationMail serviceTaskSendConfirmationMail() {
      return ServiceTaskSendConfirmationMail.INSTANCE;
    }

    public static ServiceTaskSendRejectionMail serviceTaskSendRejectionMail() {
      return ServiceTaskSendRejectionMail.INSTANCE;
    }

    public static ServiceTaskSendWelcomeMail serviceTaskSendWelcomeMail() {
      return ServiceTaskSendWelcomeMail.INSTANCE;
    }

    public static StartEventConfirmationRequired startEventConfirmationRequired() {
      return StartEventConfirmationRequired.INSTANCE;
    }

    public static StartEventSubmitRegistration startEventSubmitRegistration() {
      return StartEventSubmitRegistration.INSTANCE;
    }

    public static SubProcessConfirmMembership subProcessConfirmMembership() {
      return SubProcessConfirmMembership.INSTANCE;
    }

    public static TimerAbortAfter3HalfDays timerAbortAfter3HalfDays() {
      return TimerAbortAfter3HalfDays.INSTANCE;
    }

    public static TimerResendEveryDay timerResendEveryDay() {
      return TimerResendEveryDay.INSTANCE;
    }

    public static UserTaskConfirmMembership userTaskConfirmMembership() {
      return UserTaskConfirmMembership.INSTANCE;
    }

    public static List<FlowNode> all() {
      return List.of(
          BoundaryCompensateClaim.INSTANCE,
          CallActivityHandleRejection.INSTANCE,
          EndEventMailSentAgain.INSTANCE,
          EndEventMembershipActivated.INSTANCE,
          EndEventMembershipConfirmed.INSTANCE,
          EndEventMembershipDeclined.INSTANCE,
          EndEventMembershipRejected.INSTANCE,
          EventConfirmationRejected.INSTANCE,
          GatewayHasEmptySpots.INSTANCE,
          GatewayNotifyFork.INSTANCE,
          GatewayNotifyJoin.INSTANCE,
          ServiceTaskClaimMembership.INSTANCE,
          ServiceTaskNotifyCommunity.INSTANCE,
          ServiceTaskReSendConfirmationMail.INSTANCE,
          ServiceTaskRevokeClaim.INSTANCE,
          ServiceTaskSendConfirmationMail.INSTANCE,
          ServiceTaskSendRejectionMail.INSTANCE,
          ServiceTaskSendWelcomeMail.INSTANCE,
          StartEventConfirmationRequired.INSTANCE,
          StartEventSubmitRegistration.INSTANCE,
          SubProcessConfirmMembership.INSTANCE,
          TimerAbortAfter3HalfDays.INSTANCE,
          TimerResendEveryDay.INSTANCE,
          UserTaskConfirmMembership.INSTANCE);
    }

    public static final class BoundaryCompensateClaim extends AbstractFlowNode implements HasSuccessors<BoundaryCompensateClaim.Next>, BoundaryEvent<ServiceTaskClaimMembership> {
      public static final String ELEMENT_ID = "boundary_compensateClaim";

      public static final BoundaryCompensateClaim INSTANCE = new BoundaryCompensateClaim();

      private BoundaryCompensateClaim() {
        super(new ElementId(ELEMENT_ID), BpmnElementType.BOUNDARY_EVENT);
      }

      @Override
      public BpmnEventType getEventType() {
        return BpmnEventType.COMPENSATION;
      }

      @Override
      public ServiceTaskClaimMembership getAttachedTo() {
        return ServiceTaskClaimMembership.INSTANCE;
      }

      @Override
      public boolean isInterrupting() {
        return true;
      }

      @Override
      public Next getNext() {
        return new Next();
      }

      public static final class Next {
        public AssociatedCompensationHandler<ServiceTaskRevokeClaim> serviceTaskRevokeClaim() {
          return new AssociatedCompensationHandler<>(ServiceTaskRevokeClaim.INSTANCE);
        }
      }
    }

    public static final class CallActivityHandleRejection extends AbstractFlowNode implements HasSuccessors<CallActivityHandleRejection.Next>, CallActivity, HasVariables {
      public static final String ELEMENT_ID = "callActivity_handleRejection";

      public static final CallActivityHandleRejection INSTANCE = new CallActivityHandleRejection();

      private static final Variables VARIABLES = new Variables();

      private CallActivityHandleRejection() {
        super(new ElementId(ELEMENT_ID), BpmnElementType.CALL_ACTIVITY, "Handle rejection");
      }

      @Override
      public ProcessId getCalledProcess() {
        return new ProcessId("handleRejection");
      }

      @Override
      public Variables getVariables() {
        return VARIABLES;
      }

      @Override
      public Next getNext() {
        return new Next();
      }

      public static final class Variables extends VariableDefinitions {
        public static final VariableName.Input AGE = new VariableName.Input(ProcessVariables.AGE);

        public static final VariableName.Input MEMBERSHIP_ID = new VariableName.Input(ProcessVariables.MEMBERSHIP_ID);

        private Variables() {
        }

        @Override
        public List<VariableName> getAll() {
          return List.of(AGE, MEMBERSHIP_ID);
        }
      }

      public static final class Inputs {
        public static final InputOutputMapping AGE = new InputOutputMapping("age", "age", null);

        public static final InputOutputMapping MEMBERSHIP_ID = new InputOutputMapping("membershipId", "membershipId", null);

        private Inputs() {
        }
      }

      public static final class Next {
        public SequenceFlows<EndEventMembershipDeclined> endEventMembershipDeclined() {
          return SequenceFlows.single(new ElementId("Flow_14y1unw"), EndEventMembershipDeclined.INSTANCE);
        }
      }
    }

    public static final class EndEventMailSentAgain extends AbstractFlowNode implements Event {
      public static final String ELEMENT_ID = "endEvent_mailSentAgain";

      public static final EndEventMailSentAgain INSTANCE = new EndEventMailSentAgain();

      private EndEventMailSentAgain() {
        super(new ElementId(ELEMENT_ID), BpmnElementType.END_EVENT, "Mail sent again");
      }

      @Override
      public BpmnEventType getEventType() {
        return BpmnEventType.NONE;
      }
    }

    public static final class EndEventMembershipActivated extends AbstractFlowNode implements Event {
      public static final String ELEMENT_ID = "endEvent_membershipActivated";

      public static final EndEventMembershipActivated INSTANCE = new EndEventMembershipActivated();

      private EndEventMembershipActivated() {
        super(new ElementId(ELEMENT_ID), BpmnElementType.END_EVENT, "Membership activated");
      }

      @Override
      public BpmnEventType getEventType() {
        return BpmnEventType.NONE;
      }
    }

    public static final class EndEventMembershipConfirmed extends AbstractFlowNode implements Event {
      public static final String ELEMENT_ID = "endEvent_membershipConfirmed";

      public static final EndEventMembershipConfirmed INSTANCE = new EndEventMembershipConfirmed();

      private EndEventMembershipConfirmed() {
        super(new ElementId(ELEMENT_ID), BpmnElementType.END_EVENT, "Membership confirmed");
      }

      @Override
      public BpmnEventType getEventType() {
        return BpmnEventType.NONE;
      }
    }

    public static final class EndEventMembershipDeclined extends AbstractFlowNode implements Event, CompensationThrowEvent {
      public static final String ELEMENT_ID = "endEvent_membershipDeclined";

      public static final EndEventMembershipDeclined INSTANCE = new EndEventMembershipDeclined();

      private EndEventMembershipDeclined() {
        super(new ElementId(ELEMENT_ID), BpmnElementType.END_EVENT, "Membership declined");
      }

      @Override
      public BpmnEventType getEventType() {
        return BpmnEventType.COMPENSATION;
      }
    }

    public static final class EndEventMembershipRejected extends AbstractFlowNode implements Event {
      public static final String ELEMENT_ID = "endEvent_membershipRejected";

      public static final EndEventMembershipRejected INSTANCE = new EndEventMembershipRejected();

      private EndEventMembershipRejected() {
        super(new ElementId(ELEMENT_ID), BpmnElementType.END_EVENT, "Membership rejected");
      }

      @Override
      public BpmnEventType getEventType() {
        return BpmnEventType.NONE;
      }
    }

    public static final class EventConfirmationRejected extends AbstractFlowNode implements HasSuccessors<EventConfirmationRejected.Next>, BoundaryEvent<SubProcessConfirmMembership>, HasMessage {
      public static final String ELEMENT_ID = "event_confirmationRejected";

      public static final EventConfirmationRejected INSTANCE = new EventConfirmationRejected();

      private EventConfirmationRejected() {
        super(new ElementId(ELEMENT_ID), BpmnElementType.BOUNDARY_EVENT, "Confirmation rejected");
      }

      @Override
      public BpmnEventType getEventType() {
        return BpmnEventType.MESSAGE;
      }

      @Override
      public MessageName getMessage() {
        return Messages.CONFIRMATION_REJECTED;
      }

      @Override
      public SubProcessConfirmMembership getAttachedTo() {
        return SubProcessConfirmMembership.INSTANCE;
      }

      @Override
      public boolean isInterrupting() {
        return true;
      }

      @Override
      public Next getNext() {
        return new Next();
      }

      public static final class Next {
        public SequenceFlows<CallActivityHandleRejection> callActivityHandleRejection() {
          return SequenceFlows.single(new ElementId("Flow_153mcrs"), CallActivityHandleRejection.INSTANCE);
        }
      }
    }

    public static final class GatewayHasEmptySpots extends AbstractFlowNode implements HasSuccessors<GatewayHasEmptySpots.Next> {
      public static final String ELEMENT_ID = "gateway_hasEmptySpots";

      public static final GatewayHasEmptySpots INSTANCE = new GatewayHasEmptySpots();

      private GatewayHasEmptySpots() {
        super(new ElementId(ELEMENT_ID), BpmnElementType.EXCLUSIVE_GATEWAY, "Free seat available?");
      }

      @Override
      public Next getNext() {
        return new Next();
      }

      public static final class Next {
        public SequenceFlows<ServiceTaskSendRejectionMail> serviceTaskSendRejectionMail() {
          return SequenceFlows.single(new ElementId("Flow_0bt3531"), "No", "${!hasEmptySpots}", false, ServiceTaskSendRejectionMail.INSTANCE);
        }

        public SequenceFlows<SubProcessConfirmMembership> subProcessConfirmMembership() {
          return SequenceFlows.single(new ElementId("Flow_0camehw"), "Yes", null, true, SubProcessConfirmMembership.INSTANCE);
        }
      }
    }

    public static final class GatewayNotifyFork extends AbstractFlowNode implements HasSuccessors<GatewayNotifyFork.Next> {
      public static final String ELEMENT_ID = "gateway_notifyFork";

      public static final GatewayNotifyFork INSTANCE = new GatewayNotifyFork();

      private GatewayNotifyFork() {
        super(new ElementId(ELEMENT_ID), BpmnElementType.PARALLEL_GATEWAY);
      }

      @Override
      public Next getNext() {
        return new Next();
      }

      public static final class Next {
        public SequenceFlows<ServiceTaskNotifyCommunity> serviceTaskNotifyCommunity() {
          return SequenceFlows.single(new ElementId("Flow_1an5chz"), ServiceTaskNotifyCommunity.INSTANCE);
        }

        public SequenceFlows<ServiceTaskSendWelcomeMail> serviceTaskSendWelcomeMail() {
          return SequenceFlows.single(new ElementId("Flow_1a6of9c"), ServiceTaskSendWelcomeMail.INSTANCE);
        }
      }
    }

    public static final class GatewayNotifyJoin extends AbstractFlowNode implements HasSuccessors<GatewayNotifyJoin.Next> {
      public static final String ELEMENT_ID = "gateway_notifyJoin";

      public static final GatewayNotifyJoin INSTANCE = new GatewayNotifyJoin();

      private GatewayNotifyJoin() {
        super(new ElementId(ELEMENT_ID), BpmnElementType.PARALLEL_GATEWAY);
      }

      @Override
      public Next getNext() {
        return new Next();
      }

      public static final class Next {
        public SequenceFlows<EndEventMembershipActivated> endEventMembershipActivated() {
          return SequenceFlows.single(new ElementId("Flow_1yc0f2l"), EndEventMembershipActivated.INSTANCE);
        }
      }
    }

    public static final class ServiceTaskClaimMembership extends AbstractFlowNode implements HasSuccessors<ServiceTaskClaimMembership.Next>, HasJobType {
      public static final String ELEMENT_ID = "serviceTask_claimMembership";

      public static final ServiceTaskClaimMembership INSTANCE = new ServiceTaskClaimMembership();

      private ServiceTaskClaimMembership() {
        super(new ElementId(ELEMENT_ID), BpmnElementType.SERVICE_TASK, "Claim membership");
      }

      @Override
      public String getJobType() {
        return ServiceTasks.CLAIM_MEMBERSHIP_DELEGATE;
      }

      @Override
      public Next getNext() {
        return new Next();
      }

      public static final class Next {
        public AttachedBoundaryEvent<BoundaryCompensateClaim> boundaryCompensateClaim() {
          return new AttachedBoundaryEvent<>(BoundaryCompensateClaim.INSTANCE);
        }

        public SequenceFlows<GatewayHasEmptySpots> gatewayHasEmptySpots() {
          return SequenceFlows.single(new ElementId("Flow_0hlnr3k"), GatewayHasEmptySpots.INSTANCE);
        }
      }
    }

    public static final class ServiceTaskNotifyCommunity extends AbstractFlowNode implements HasSuccessors<ServiceTaskNotifyCommunity.Next>, HasJobType {
      public static final String ELEMENT_ID = "serviceTask_notifyCommunity";

      public static final ServiceTaskNotifyCommunity INSTANCE = new ServiceTaskNotifyCommunity();

      private ServiceTaskNotifyCommunity() {
        super(new ElementId(ELEMENT_ID), BpmnElementType.SERVICE_TASK, "Notify community");
      }

      @Override
      public String getJobType() {
        return ServiceTasks.NOTIFY_COMMUNITY_DELEGATE;
      }

      @Override
      public Next getNext() {
        return new Next();
      }

      public static final class Next {
        public SequenceFlows<GatewayNotifyJoin> gatewayNotifyJoin() {
          return SequenceFlows.single(new ElementId("Flow_12q7mbd"), GatewayNotifyJoin.INSTANCE);
        }
      }
    }

    public static final class ServiceTaskReSendConfirmationMail extends AbstractFlowNode implements HasSuccessors<ServiceTaskReSendConfirmationMail.Next>, HasJobType {
      public static final String ELEMENT_ID = "serviceTask_reSendConfirmationMail";

      public static final ServiceTaskReSendConfirmationMail INSTANCE = new ServiceTaskReSendConfirmationMail();

      private ServiceTaskReSendConfirmationMail() {
        super(new ElementId(ELEMENT_ID), BpmnElementType.SERVICE_TASK, "Re-Send confirmation mail");
      }

      @Override
      public String getJobType() {
        return ServiceTasks.RE_SEND_CONFIRMATION_MAIL_DELEGATE;
      }

      @Override
      public Next getNext() {
        return new Next();
      }

      public static final class Next {
        public SequenceFlows<EndEventMailSentAgain> endEventMailSentAgain() {
          return SequenceFlows.single(new ElementId("Flow_03vzvil"), EndEventMailSentAgain.INSTANCE);
        }
      }
    }

    public static final class ServiceTaskRevokeClaim extends AbstractFlowNode implements HasJobType {
      public static final String ELEMENT_ID = "serviceTask_revokeClaim";

      public static final ServiceTaskRevokeClaim INSTANCE = new ServiceTaskRevokeClaim();

      private ServiceTaskRevokeClaim() {
        super(new ElementId(ELEMENT_ID), BpmnElementType.SERVICE_TASK, "Revoke claim");
      }

      @Override
      public String getJobType() {
        return ServiceTasks.REVOKE_CLAIM_DELEGATE;
      }
    }

    public static final class ServiceTaskSendConfirmationMail extends AbstractFlowNode implements HasSuccessors<ServiceTaskSendConfirmationMail.Next>, HasJobType {
      public static final String ELEMENT_ID = "serviceTask_sendConfirmationMail";

      public static final ServiceTaskSendConfirmationMail INSTANCE = new ServiceTaskSendConfirmationMail();

      private ServiceTaskSendConfirmationMail() {
        super(new ElementId(ELEMENT_ID), BpmnElementType.SERVICE_TASK, "Send confirmation mail");
      }

      @Override
      public String getJobType() {
        return ServiceTasks.SEND_CONFIRMATION_MAIL_DELEGATE;
      }

      @Override
      public Next getNext() {
        return new Next();
      }

      public static final class Next {
        public SequenceFlows<UserTaskConfirmMembership> userTaskConfirmMembership() {
          return SequenceFlows.single(new ElementId("Flow_1wb7scj"), UserTaskConfirmMembership.INSTANCE);
        }
      }
    }

    public static final class ServiceTaskSendRejectionMail extends AbstractFlowNode implements HasSuccessors<ServiceTaskSendRejectionMail.Next>, HasJobType {
      public static final String ELEMENT_ID = "serviceTask_sendRejectionMail";

      public static final ServiceTaskSendRejectionMail INSTANCE = new ServiceTaskSendRejectionMail();

      private ServiceTaskSendRejectionMail() {
        super(new ElementId(ELEMENT_ID), BpmnElementType.SERVICE_TASK, "Send rejection mail");
      }

      @Override
      public String getJobType() {
        return ServiceTasks.SEND_REJECTION_MAIL_DELEGATE;
      }

      @Override
      public Next getNext() {
        return new Next();
      }

      public static final class Next {
        public SequenceFlows<EndEventMembershipRejected> endEventMembershipRejected() {
          return SequenceFlows.single(new ElementId("Flow_10ryvaz"), EndEventMembershipRejected.INSTANCE);
        }
      }
    }

    public static final class ServiceTaskSendWelcomeMail extends AbstractFlowNode implements HasSuccessors<ServiceTaskSendWelcomeMail.Next>, HasJobType {
      public static final String ELEMENT_ID = "serviceTask_sendWelcomeMail";

      public static final ServiceTaskSendWelcomeMail INSTANCE = new ServiceTaskSendWelcomeMail();

      private ServiceTaskSendWelcomeMail() {
        super(new ElementId(ELEMENT_ID), BpmnElementType.SERVICE_TASK, "Send Welcome Mail");
      }

      @Override
      public String getJobType() {
        return ServiceTasks.SEND_WELCOME_MAIL_DELEGATE;
      }

      @Override
      public Next getNext() {
        return new Next();
      }

      public static final class Next {
        public SequenceFlows<GatewayNotifyJoin> gatewayNotifyJoin() {
          return SequenceFlows.single(new ElementId("Flow_0arsuyz"), GatewayNotifyJoin.INSTANCE);
        }
      }
    }

    public static final class StartEventConfirmationRequired extends AbstractFlowNode implements HasSuccessors<StartEventConfirmationRequired.Next>, Event {
      public static final String ELEMENT_ID = "startEvent_confirmationRequired";

      public static final StartEventConfirmationRequired INSTANCE = new StartEventConfirmationRequired();

      private StartEventConfirmationRequired() {
        super(new ElementId(ELEMENT_ID), BpmnElementType.START_EVENT, "Confirmation required");
      }

      @Override
      public BpmnEventType getEventType() {
        return BpmnEventType.NONE;
      }

      @Override
      public Next getNext() {
        return new Next();
      }

      public static final class Next {
        public SequenceFlows<ServiceTaskSendConfirmationMail> serviceTaskSendConfirmationMail() {
          return SequenceFlows.single(new ElementId("Flow_1y9mu7r"), ServiceTaskSendConfirmationMail.INSTANCE);
        }
      }
    }

    public static final class StartEventSubmitRegistration extends AbstractFlowNode implements HasSuccessors<StartEventSubmitRegistration.Next>, Event, HasMessage {
      public static final String ELEMENT_ID = "startEvent_submitRegistration";

      public static final StartEventSubmitRegistration INSTANCE = new StartEventSubmitRegistration();

      private StartEventSubmitRegistration() {
        super(new ElementId(ELEMENT_ID), BpmnElementType.START_EVENT, "Submit registration form");
      }

      @Override
      public BpmnEventType getEventType() {
        return BpmnEventType.MESSAGE;
      }

      @Override
      public MessageName getMessage() {
        return Messages.SUBSCRIPTION_REQUESTED;
      }

      @Override
      public Next getNext() {
        return new Next();
      }

      public static final class Next {
        public SequenceFlows<ServiceTaskClaimMembership> serviceTaskClaimMembership() {
          return SequenceFlows.single(new ElementId("Flow_0p7ko1g"), ServiceTaskClaimMembership.INSTANCE);
        }
      }
    }

    public static final class SubProcessConfirmMembership extends AbstractFlowNode implements HasSuccessors<SubProcessConfirmMembership.Next>, FlowScope<SubProcessConfirmMembership.Start> {
      public static final String ELEMENT_ID = "subProcess_confirmMembership";

      public static final SubProcessConfirmMembership INSTANCE = new SubProcessConfirmMembership();

      private SubProcessConfirmMembership() {
        super(new ElementId(ELEMENT_ID), BpmnElementType.SUB_PROCESS, "Confirm membership");
      }

      @Override
      public Next getNext() {
        return new Next();
      }

      @Override
      public Start getStartEvents() {
        return new Start();
      }

      public static final class Next {
        public AttachedBoundaryEvent<EventConfirmationRejected> eventConfirmationRejected() {
          return new AttachedBoundaryEvent<>(EventConfirmationRejected.INSTANCE);
        }

        public SequenceFlows<GatewayNotifyFork> gatewayNotifyFork() {
          return SequenceFlows.single(new ElementId("Flow_1j9l21y"), GatewayNotifyFork.INSTANCE);
        }

        public AttachedBoundaryEvent<TimerAbortAfter3HalfDays> timerAbortAfter3HalfDays() {
          return new AttachedBoundaryEvent<>(TimerAbortAfter3HalfDays.INSTANCE);
        }

        public AttachedBoundaryEvent<TimerResendEveryDay> timerResendEveryDay() {
          return new AttachedBoundaryEvent<>(TimerResendEveryDay.INSTANCE);
        }
      }

      public static final class Start {
        public StartEventConfirmationRequired startEventConfirmationRequired() {
          return StartEventConfirmationRequired.INSTANCE;
        }
      }
    }

    public static final class TimerAbortAfter3HalfDays extends AbstractFlowNode implements HasSuccessors<TimerAbortAfter3HalfDays.Next>, BoundaryEvent<SubProcessConfirmMembership>, TimerEvent {
      public static final String ELEMENT_ID = "timer_abortAfter3HalfDays";

      public static final TimerAbortAfter3HalfDays INSTANCE = new TimerAbortAfter3HalfDays();

      private TimerAbortAfter3HalfDays() {
        super(new ElementId(ELEMENT_ID), BpmnElementType.BOUNDARY_EVENT, "After 3 1/2 days");
      }

      @Override
      public BpmnEventType getEventType() {
        return BpmnEventType.TIMER;
      }

      @Override
      public BpmnTimer getTimer() {
        return new BpmnTimer(TimerType.DURATION, "P3DT12H");
      }

      @Override
      public SubProcessConfirmMembership getAttachedTo() {
        return SubProcessConfirmMembership.INSTANCE;
      }

      @Override
      public boolean isInterrupting() {
        return true;
      }

      @Override
      public Next getNext() {
        return new Next();
      }

      public static final class Next {
        public SequenceFlows<CallActivityHandleRejection> callActivityHandleRejection() {
          return SequenceFlows.single(new ElementId("Flow_0ho2dhw"), CallActivityHandleRejection.INSTANCE);
        }
      }
    }

    public static final class TimerResendEveryDay extends AbstractFlowNode implements HasSuccessors<TimerResendEveryDay.Next>, BoundaryEvent<SubProcessConfirmMembership>, TimerEvent {
      public static final String ELEMENT_ID = "timer_resendEveryDay";

      public static final TimerResendEveryDay INSTANCE = new TimerResendEveryDay();

      private TimerResendEveryDay() {
        super(new ElementId(ELEMENT_ID), BpmnElementType.BOUNDARY_EVENT, "Every day");
      }

      @Override
      public BpmnEventType getEventType() {
        return BpmnEventType.TIMER;
      }

      @Override
      public BpmnTimer getTimer() {
        return new BpmnTimer(TimerType.CYCLE, "R/P1D");
      }

      @Override
      public SubProcessConfirmMembership getAttachedTo() {
        return SubProcessConfirmMembership.INSTANCE;
      }

      @Override
      public boolean isInterrupting() {
        return false;
      }

      @Override
      public Next getNext() {
        return new Next();
      }

      public static final class Next {
        public SequenceFlows<ServiceTaskReSendConfirmationMail> serviceTaskReSendConfirmationMail(
            ) {
          return SequenceFlows.single(new ElementId("Flow_1unns5i"), ServiceTaskReSendConfirmationMail.INSTANCE);
        }
      }
    }

    public static final class UserTaskConfirmMembership extends AbstractFlowNode implements HasSuccessors<UserTaskConfirmMembership.Next> {
      public static final String ELEMENT_ID = "userTask_confirmMembership";

      public static final UserTaskConfirmMembership INSTANCE = new UserTaskConfirmMembership();

      private UserTaskConfirmMembership() {
        super(new ElementId(ELEMENT_ID), BpmnElementType.USER_TASK, "Confirm membership");
      }

      @Override
      public Next getNext() {
        return new Next();
      }

      public static final class Next {
        public SequenceFlows<EndEventMembershipConfirmed> endEventMembershipConfirmed() {
          return SequenceFlows.single(new ElementId("Flow_0w9368p"), EndEventMembershipConfirmed.INSTANCE);
        }
      }
    }
  }
}
