// Generated by bpmn-to-code
package io.miragon.training.adapter.process;

import io.miragon.bpmn.runtime.MessageName;
import java.util.List;

/**
 * BPMN message names used to correlate messages to running process instances.
 */
public final class Messages {
  public static final MessageName SUBSCRIPTION_REQUESTED = new MessageName("Message_SubscriptionRequested");

  private Messages() {
  }

  public static List<MessageName> all() {
    return List.of(
        SUBSCRIPTION_REQUESTED);
  }
}
