// Generated by bpmn-to-code
package io.miragon.training.adapter.process;

import java.util.List;

/**
 * Job worker task types used in {@code @JobWorker(type = ServiceTasks.X)} annotations.
 * Kept as {@code public static final String} because annotation arguments must be compile-time constants.
 */
public final class ServiceTasks {
  public static final String CLAIM_MEMBERSHIP_DELEGATE = "#{claimMembershipDelegate}";

  public static final String SEND_CONFIRMATION_MAIL_DELEGATE = "#{sendConfirmationMailDelegate}";

  public static final String SEND_REJECTION_MAIL_DELEGATE = "#{sendRejectionMailDelegate}";

  public static final String SEND_WELCOME_MAIL_DELEGATE = "#{sendWelcomeMailDelegate}";

  private ServiceTasks() {
  }

  public static List<String> all() {
    return List.of(
        CLAIM_MEMBERSHIP_DELEGATE,
        SEND_CONFIRMATION_MAIL_DELEGATE,
        SEND_REJECTION_MAIL_DELEGATE,
        SEND_WELCOME_MAIL_DELEGATE);
  }
}
