// Generated by bpmn-to-code
package io.miragon.training.adapter.process;

import io.miragon.bpmn.runtime.AbstractFlowNode;
import io.miragon.bpmn.runtime.BpmnElementType;
import io.miragon.bpmn.runtime.BpmnEngine;
import io.miragon.bpmn.runtime.BpmnEventType;
import io.miragon.bpmn.runtime.ElementId;
import io.miragon.bpmn.runtime.Event;
import io.miragon.bpmn.runtime.FlowNode;
import io.miragon.bpmn.runtime.HasJobType;
import io.miragon.bpmn.runtime.HasMessage;
import io.miragon.bpmn.runtime.HasSuccessors;
import io.miragon.bpmn.runtime.MessageName;
import io.miragon.bpmn.runtime.ProcessId;
import io.miragon.bpmn.runtime.SequenceFlows;
import java.util.List;

public final class SubscribeNewsletterProcessApi {
  public static final ProcessId PROCESS_ID = new ProcessId("subscribeNewsletter");

  public static final BpmnEngine PROCESS_ENGINE = BpmnEngine.CAMUNDA_7;

  private SubscribeNewsletterProcessApi() {
  }

  /**
   * Typed navigation over the process flow: one nested class per BPMN element.
   */
  public static final class FlowNodes {
    private FlowNodes() {
    }

    public static EndEventMembershipConfirmed endEventMembershipConfirmed() {
      return EndEventMembershipConfirmed.INSTANCE;
    }

    public static EndEventMembershipRejected endEventMembershipRejected() {
      return EndEventMembershipRejected.INSTANCE;
    }

    public static GatewayHasEmptySpots gatewayHasEmptySpots() {
      return GatewayHasEmptySpots.INSTANCE;
    }

    public static ServiceTaskClaimMembership serviceTaskClaimMembership() {
      return ServiceTaskClaimMembership.INSTANCE;
    }

    public static ServiceTaskSendConfirmationMail serviceTaskSendConfirmationMail() {
      return ServiceTaskSendConfirmationMail.INSTANCE;
    }

    public static ServiceTaskSendRejectionMail serviceTaskSendRejectionMail() {
      return ServiceTaskSendRejectionMail.INSTANCE;
    }

    public static ServiceTaskSendWelcomeMail serviceTaskSendWelcomeMail() {
      return ServiceTaskSendWelcomeMail.INSTANCE;
    }

    public static StartEventSubmitRegistration startEventSubmitRegistration() {
      return StartEventSubmitRegistration.INSTANCE;
    }

    public static UserTaskConfirmMembership userTaskConfirmMembership() {
      return UserTaskConfirmMembership.INSTANCE;
    }

    public static List<FlowNode> all() {
      return List.of(
          EndEventMembershipConfirmed.INSTANCE,
          EndEventMembershipRejected.INSTANCE,
          GatewayHasEmptySpots.INSTANCE,
          ServiceTaskClaimMembership.INSTANCE,
          ServiceTaskSendConfirmationMail.INSTANCE,
          ServiceTaskSendRejectionMail.INSTANCE,
          ServiceTaskSendWelcomeMail.INSTANCE,
          StartEventSubmitRegistration.INSTANCE,
          UserTaskConfirmMembership.INSTANCE);
    }

    public static final class EndEventMembershipConfirmed extends AbstractFlowNode implements Event {
      public static final String ELEMENT_ID = "endEvent_membershipConfirmed";

      public static final EndEventMembershipConfirmed INSTANCE = new EndEventMembershipConfirmed();

      private EndEventMembershipConfirmed() {
        super(new ElementId(ELEMENT_ID), BpmnElementType.END_EVENT, "Membership confirmed");
      }

      @Override
      public BpmnEventType getEventType() {
        return BpmnEventType.NONE;
      }
    }

    public static final class EndEventMembershipRejected extends AbstractFlowNode implements Event {
      public static final String ELEMENT_ID = "endEvent_membershipRejected";

      public static final EndEventMembershipRejected INSTANCE = new EndEventMembershipRejected();

      private EndEventMembershipRejected() {
        super(new ElementId(ELEMENT_ID), BpmnElementType.END_EVENT, "Membership rejected");
      }

      @Override
      public BpmnEventType getEventType() {
        return BpmnEventType.NONE;
      }
    }

    public static final class GatewayHasEmptySpots extends AbstractFlowNode implements HasSuccessors<GatewayHasEmptySpots.Next> {
      public static final String ELEMENT_ID = "gateway_hasEmptySpots";

      public static final GatewayHasEmptySpots INSTANCE = new GatewayHasEmptySpots();

      private GatewayHasEmptySpots() {
        super(new ElementId(ELEMENT_ID), BpmnElementType.EXCLUSIVE_GATEWAY, "Free seat available?");
      }

      @Override
      public Next getNext() {
        return new Next();
      }

      public static final class Next {
        public SequenceFlows<ServiceTaskSendConfirmationMail> serviceTaskSendConfirmationMail() {
          return SequenceFlows.single(new ElementId("Flow_1pl6nn4"), "Yes", null, true, ServiceTaskSendConfirmationMail.INSTANCE);
        }

        public SequenceFlows<ServiceTaskSendRejectionMail> serviceTaskSendRejectionMail() {
          return SequenceFlows.single(new ElementId("Flow_0cad0i8"), "No", "${!hasEmptySpots}", false, ServiceTaskSendRejectionMail.INSTANCE);
        }
      }
    }

    public static final class ServiceTaskClaimMembership extends AbstractFlowNode implements HasSuccessors<ServiceTaskClaimMembership.Next>, HasJobType {
      public static final String ELEMENT_ID = "serviceTask_claimMembership";

      public static final ServiceTaskClaimMembership INSTANCE = new ServiceTaskClaimMembership();

      private ServiceTaskClaimMembership() {
        super(new ElementId(ELEMENT_ID), BpmnElementType.SERVICE_TASK, "Claim membership");
      }

      @Override
      public String getJobType() {
        return ServiceTasks.CLAIM_MEMBERSHIP_DELEGATE;
      }

      @Override
      public Next getNext() {
        return new Next();
      }

      public static final class Next {
        public SequenceFlows<GatewayHasEmptySpots> gatewayHasEmptySpots() {
          return SequenceFlows.single(new ElementId("Flow_1spthma"), GatewayHasEmptySpots.INSTANCE);
        }
      }
    }

    public static final class ServiceTaskSendConfirmationMail extends AbstractFlowNode implements HasSuccessors<ServiceTaskSendConfirmationMail.Next>, HasJobType {
      public static final String ELEMENT_ID = "serviceTask_sendConfirmationMail";

      public static final ServiceTaskSendConfirmationMail INSTANCE = new ServiceTaskSendConfirmationMail();

      private ServiceTaskSendConfirmationMail() {
        super(new ElementId(ELEMENT_ID), BpmnElementType.SERVICE_TASK, "Send confirmation mail");
      }

      @Override
      public String getJobType() {
        return ServiceTasks.SEND_CONFIRMATION_MAIL_DELEGATE;
      }

      @Override
      public Next getNext() {
        return new Next();
      }

      public static final class Next {
        public SequenceFlows<UserTaskConfirmMembership> userTaskConfirmMembership() {
          return SequenceFlows.single(new ElementId("Flow_13584xc"), UserTaskConfirmMembership.INSTANCE);
        }
      }
    }

    public static final class ServiceTaskSendRejectionMail extends AbstractFlowNode implements HasSuccessors<ServiceTaskSendRejectionMail.Next>, HasJobType {
      public static final String ELEMENT_ID = "serviceTask_sendRejectionMail";

      public static final ServiceTaskSendRejectionMail INSTANCE = new ServiceTaskSendRejectionMail();

      private ServiceTaskSendRejectionMail() {
        super(new ElementId(ELEMENT_ID), BpmnElementType.SERVICE_TASK, "Send rejection mail");
      }

      @Override
      public String getJobType() {
        return ServiceTasks.SEND_REJECTION_MAIL_DELEGATE;
      }

      @Override
      public Next getNext() {
        return new Next();
      }

      public static final class Next {
        public SequenceFlows<EndEventMembershipRejected> endEventMembershipRejected() {
          return SequenceFlows.single(new ElementId("Flow_0loiw0z"), EndEventMembershipRejected.INSTANCE);
        }
      }
    }

    public static final class ServiceTaskSendWelcomeMail extends AbstractFlowNode implements HasSuccessors<ServiceTaskSendWelcomeMail.Next>, HasJobType {
      public static final String ELEMENT_ID = "serviceTask_sendWelcomeMail";

      public static final ServiceTaskSendWelcomeMail INSTANCE = new ServiceTaskSendWelcomeMail();

      private ServiceTaskSendWelcomeMail() {
        super(new ElementId(ELEMENT_ID), BpmnElementType.SERVICE_TASK, "Send Welcome Mail");
      }

      @Override
      public String getJobType() {
        return ServiceTasks.SEND_WELCOME_MAIL_DELEGATE;
      }

      @Override
      public Next getNext() {
        return new Next();
      }

      public static final class Next {
        public SequenceFlows<EndEventMembershipConfirmed> endEventMembershipConfirmed() {
          return SequenceFlows.single(new ElementId("Flow_1s74azu"), EndEventMembershipConfirmed.INSTANCE);
        }
      }
    }

    public static final class StartEventSubmitRegistration extends AbstractFlowNode implements HasSuccessors<StartEventSubmitRegistration.Next>, Event, HasMessage {
      public static final String ELEMENT_ID = "startEvent_submitRegistration";

      public static final StartEventSubmitRegistration INSTANCE = new StartEventSubmitRegistration();

      private StartEventSubmitRegistration() {
        super(new ElementId(ELEMENT_ID), BpmnElementType.START_EVENT, "Submit registration form");
      }

      @Override
      public BpmnEventType getEventType() {
        return BpmnEventType.MESSAGE;
      }

      @Override
      public MessageName getMessage() {
        return Messages.SUBSCRIPTION_REQUESTED;
      }

      @Override
      public Next getNext() {
        return new Next();
      }

      public static final class Next {
        public SequenceFlows<ServiceTaskClaimMembership> serviceTaskClaimMembership() {
          return SequenceFlows.single(new ElementId("Flow_0p7ko1g"), ServiceTaskClaimMembership.INSTANCE);
        }
      }
    }

    public static final class UserTaskConfirmMembership extends AbstractFlowNode implements HasSuccessors<UserTaskConfirmMembership.Next> {
      public static final String ELEMENT_ID = "userTask_confirmMembership";

      public static final UserTaskConfirmMembership INSTANCE = new UserTaskConfirmMembership();

      private UserTaskConfirmMembership() {
        super(new ElementId(ELEMENT_ID), BpmnElementType.USER_TASK, "Confirm membership");
      }

      @Override
      public Next getNext() {
        return new Next();
      }

      public static final class Next {
        public SequenceFlows<ServiceTaskSendWelcomeMail> serviceTaskSendWelcomeMail() {
          return SequenceFlows.single(new ElementId("Flow_0ya530i"), ServiceTaskSendWelcomeMail.INSTANCE);
        }
      }
    }
  }
}
