// Generated by bpmn-to-code
package io.miragon.training.adapter.process;

import io.miragon.bpmn.runtime.BpmnEngine;
import io.miragon.bpmn.runtime.BpmnFlow;
import io.miragon.bpmn.runtime.BpmnRelations;
import io.miragon.bpmn.runtime.ElementId;
import io.miragon.bpmn.runtime.ProcessId;
import java.util.List;

public final class HandleRejectionProcessApi {
  public static final ProcessId PROCESS_ID = new ProcessId("handleRejection");

  public static final BpmnEngine PROCESS_ENGINE = BpmnEngine.CAMUNDA_7;

  /**
   * BPMN element ids as declared in the source model.
   * Typically used in process-level tests or when searching for tasks.
   * Worker runtime code rarely needs these.
   */
  public static final class Elements {
    public static final ElementId END_EVENT_ACCEPT_REJECTION = new ElementId("endEvent_acceptRejection");

    public static final ElementId END_EVENT_TRIED_TO_REACQUIRE = new ElementId("endEvent_triedToReacquire");

    public static final ElementId GATEWAY_HIGH_VALUE = new ElementId("gateway_highValue");

    public static final ElementId SERVICE_TASK_CATEGORIZE_APPLICANT = new ElementId("serviceTask_categorizeApplicant");

    public static final ElementId START_EVENT_CONFIRMATION_REJECTED = new ElementId("startEvent_confirmationRejected");

    public static final ElementId USER_TASK_WRITE_REGRET_MAIL = new ElementId("userTask_writeRegretMail");
  }

  /**
   * Sequence flows between BPMN elements.
   * Mainly useful for process-model tooling, tests, and AI-agent consumers reasoning about the process shape.
   * Worker code typically does not need these.
   */
  public static final class Flows {
    public static final BpmnFlow FLOW_07_Y_997_B = new BpmnFlow("Flow_07y997b", "Yes", "gateway_highValue", "userTask_writeRegretMail", "${isHighValue}", false);

    public static final BpmnFlow FLOW_0_GVF_8_ZJ = new BpmnFlow("Flow_0gvf8zj", null, "serviceTask_categorizeApplicant", "gateway_highValue", null, false);

    public static final BpmnFlow FLOW_0_VQWQSJ = new BpmnFlow("Flow_0vqwqsj", null, "startEvent_confirmationRejected", "serviceTask_categorizeApplicant", null, false);

    public static final BpmnFlow FLOW_1_IMJD_1_V = new BpmnFlow("Flow_1imjd1v", "No", "gateway_highValue", "endEvent_acceptRejection", null, true);

    public static final BpmnFlow FLOW_1_UFK_6_O_2 = new BpmnFlow("Flow_1ufk6o2", null, "userTask_writeRegretMail", "endEvent_triedToReacquire", null, false);
  }

  /**
   * Per-element graph metadata (elementType / previousElements / followingElements / parentId / boundary attachments).
   * Intended for tooling and tests, not worker runtime code.
   */
  public static final class Relations {
    public static final BpmnRelations END_EVENT_ACCEPT_REJECTION = new BpmnRelations("Accept rejection", List.of("gateway_highValue"), List.of(), null, null, List.of(), "END_EVENT");

    public static final BpmnRelations END_EVENT_TRIED_TO_REACQUIRE = new BpmnRelations("Tried to reaquire applicant", List.of("userTask_writeRegretMail"), List.of(), null, null, List.of(), "END_EVENT");

    public static final BpmnRelations GATEWAY_HIGH_VALUE = new BpmnRelations("High value?", List.of("serviceTask_categorizeApplicant"), List.of("userTask_writeRegretMail", "endEvent_acceptRejection"), null, null, List.of(), "EXCLUSIVE_GATEWAY");

    public static final BpmnRelations SERVICE_TASK_CATEGORIZE_APPLICANT = new BpmnRelations("Categorize applicant", List.of("startEvent_confirmationRejected"), List.of("gateway_highValue"), null, null, List.of(), "BUSINESS_RULE_TASK");

    public static final BpmnRelations START_EVENT_CONFIRMATION_REJECTED = new BpmnRelations("Confirmation rejected", List.of(), List.of("serviceTask_categorizeApplicant"), null, null, List.of(), "START_EVENT");

    public static final BpmnRelations USER_TASK_WRITE_REGRET_MAIL = new BpmnRelations("Write an email expressing regret", List.of("gateway_highValue"), List.of("endEvent_triedToReacquire"), null, null, List.of(), "USER_TASK");
  }
}
