// Generated by bpmn-to-code
package io.miragon.training.adapter.process;

import java.util.List;

/**
 * Names of the process variables used in {@code @Variable(name = ProcessVariables.X)} annotations.
 * Kept as {@code public static final String} because annotation arguments must be compile-time constants.
 */
public final class ProcessVariables {
  public static final String AGE = "age";

  public static final String MEMBERSHIP_ID = "membershipId";

  private ProcessVariables() {
  }

  public static List<String> all() {
    return List.of(
        AGE,
        MEMBERSHIP_ID);
  }
}
