// Generated by bpmn-to-code
package io.miragon.training.adapter.process;

import java.util.List;

/**
 * Job worker task types used in {@code @JobWorker(type = ServiceTasks.X)} annotations.
 * Kept as {@code public static final String} because annotation arguments must be compile-time constants.
 */
public final class ServiceTasks {
  public static final String CLAIM_MEMBERSHIP = "claimMembership";

  public static final String NOTIFY_COMMUNITY = "notifyCommunity";

  public static final String RE_SEND_CONFIRMATION_MAIL = "reSendConfirmationMail";

  public static final String REVOKE_CLAIM = "revokeClaim";

  public static final String SEND_CONFIRMATION_MAIL = "sendConfirmationMail";

  public static final String SEND_REJECTION_MAIL = "sendRejectionMail";

  public static final String SEND_WELCOME_MAIL = "sendWelcomeMail";

  private ServiceTasks() {
  }

  public static List<String> all() {
    return List.of(
        CLAIM_MEMBERSHIP,
        NOTIFY_COMMUNITY,
        RE_SEND_CONFIRMATION_MAIL,
        REVOKE_CLAIM,
        SEND_CONFIRMATION_MAIL,
        SEND_REJECTION_MAIL,
        SEND_WELCOME_MAIL);
  }
}
