// Generated by bpmn-to-code
package io.miragon.training.adapter.process;

import io.miragon.bpmn.runtime.BpmnEngine;
import io.miragon.bpmn.runtime.BpmnFlow;
import io.miragon.bpmn.runtime.BpmnRelations;
import io.miragon.bpmn.runtime.ElementId;
import io.miragon.bpmn.runtime.ProcessId;
import io.miragon.bpmn.runtime.SignalName;
import java.lang.String;
import java.util.List;

public final class SendWelcomeKitProcessApi {
  public static final ProcessId PROCESS_ID = new ProcessId("sendWelcomeKit");

  public static final BpmnEngine PROCESS_ENGINE = BpmnEngine.CAMUNDA_7;

  /**
   * BPMN element ids as declared in the source model.
   * Typically used in process-level tests or when searching for tasks.
   * Worker runtime code rarely needs these.
   */
  public static final class Elements {
    public static final ElementId END_EVENT_WELCOME_KIT_SHIPPED = new ElementId("endEvent_welcomeKitShipped");

    public static final ElementId GATEWAY_START = new ElementId("gateway_start");

    public static final ElementId SERVICE_TASK_SHIP_WELCOME_KIT = new ElementId("serviceTask_shipWelcomeKit");

    public static final ElementId START_EVENT_MANUAL_START = new ElementId("startEvent_manualStart");

    public static final ElementId START_EVENT_MEMBER_ACTIVATED = new ElementId("startEvent_memberActivated");
  }

  /**
   * Job worker task types used in {@code @JobWorker(type = ServiceTasks.X)} annotations.
   * Kept as {@code public static final String} because annotation arguments must be compile-time constants.
   */
  public static final class ServiceTasks {
    public static final String SHIP_WELCOME_KIT = "shipWelcomeKit";
  }

  public static final class Signals {
    public static final SignalName SIGNAL_MEMBER_ACTIVATED = new SignalName("Signal_MemberActivated");
  }

  /**
   * Sequence flows between BPMN elements.
   * Mainly useful for process-model tooling, tests, and AI-agent consumers reasoning about the process shape.
   * Worker code typically does not need these.
   */
  public static final class Flows {
    public static final BpmnFlow FLOW_MANUAL_TO_START = new BpmnFlow("Flow_manualToStart", null, "startEvent_manualStart", "gateway_start", null, false);

    public static final BpmnFlow FLOW_SHIP_TO_END = new BpmnFlow("Flow_shipToEnd", null, "serviceTask_shipWelcomeKit", "endEvent_welcomeKitShipped", null, false);

    public static final BpmnFlow FLOW_SIGNAL_TO_START = new BpmnFlow("Flow_signalToStart", null, "startEvent_memberActivated", "gateway_start", null, false);

    public static final BpmnFlow FLOW_START_TO_SHIP = new BpmnFlow("Flow_startToShip", null, "gateway_start", "serviceTask_shipWelcomeKit", null, false);
  }

  /**
   * Per-element graph metadata (elementType / previousElements / followingElements / parentId / boundary attachments).
   * Intended for tooling and tests, not worker runtime code.
   */
  public static final class Relations {
    public static final BpmnRelations END_EVENT_WELCOME_KIT_SHIPPED = new BpmnRelations("Welcome kit shipped", List.of("serviceTask_shipWelcomeKit"), List.of(), null, null, List.of(), "END_EVENT");

    public static final BpmnRelations GATEWAY_START = new BpmnRelations(null, List.of("startEvent_memberActivated", "startEvent_manualStart"), List.of("serviceTask_shipWelcomeKit"), null, null, List.of(), "EXCLUSIVE_GATEWAY");

    public static final BpmnRelations SERVICE_TASK_SHIP_WELCOME_KIT = new BpmnRelations("Ship welcome kit", List.of("gateway_start"), List.of("endEvent_welcomeKitShipped"), null, null, List.of(), "SERVICE_TASK");

    public static final BpmnRelations START_EVENT_MANUAL_START = new BpmnRelations("Manual start (testing / fallback)", List.of(), List.of("gateway_start"), null, null, List.of(), "START_EVENT");

    public static final BpmnRelations START_EVENT_MEMBER_ACTIVATED = new BpmnRelations("New member activated", List.of(), List.of("gateway_start"), null, null, List.of(), "SIGNAL_START_EVENT");
  }
}
