// Generated by bpmn-to-code
package io.miragon.training.adapter.process;

import io.miragon.bpmn.runtime.AbstractFlowNode;
import io.miragon.bpmn.runtime.BpmnElementType;
import io.miragon.bpmn.runtime.BpmnEngine;
import io.miragon.bpmn.runtime.BpmnEventType;
import io.miragon.bpmn.runtime.ElementId;
import io.miragon.bpmn.runtime.Event;
import io.miragon.bpmn.runtime.FlowNode;
import io.miragon.bpmn.runtime.HasJobType;
import io.miragon.bpmn.runtime.HasSuccessors;
import io.miragon.bpmn.runtime.ProcessId;
import io.miragon.bpmn.runtime.SequenceFlows;
import io.miragon.bpmn.runtime.SignalEvent;
import io.miragon.bpmn.runtime.SignalName;
import java.util.List;

public final class SendWelcomeKitProcessApi {
  public static final ProcessId PROCESS_ID = new ProcessId("sendWelcomeKit");

  public static final BpmnEngine PROCESS_ENGINE = BpmnEngine.CAMUNDA_7;

  private SendWelcomeKitProcessApi() {
  }

  /**
   * Typed navigation over the process flow: one nested class per BPMN element.
   */
  public static final class FlowNodes {
    private FlowNodes() {
    }

    public static EndEventWelcomeKitShipped endEventWelcomeKitShipped() {
      return EndEventWelcomeKitShipped.INSTANCE;
    }

    public static GatewayStart gatewayStart() {
      return GatewayStart.INSTANCE;
    }

    public static ServiceTaskShipWelcomeKit serviceTaskShipWelcomeKit() {
      return ServiceTaskShipWelcomeKit.INSTANCE;
    }

    public static StartEventManualStart startEventManualStart() {
      return StartEventManualStart.INSTANCE;
    }

    public static StartEventMemberActivated startEventMemberActivated() {
      return StartEventMemberActivated.INSTANCE;
    }

    public static List<FlowNode> all() {
      return List.of(
          EndEventWelcomeKitShipped.INSTANCE,
          GatewayStart.INSTANCE,
          ServiceTaskShipWelcomeKit.INSTANCE,
          StartEventManualStart.INSTANCE,
          StartEventMemberActivated.INSTANCE);
    }

    public static final class EndEventWelcomeKitShipped extends AbstractFlowNode implements Event {
      public static final String ELEMENT_ID = "endEvent_welcomeKitShipped";

      public static final EndEventWelcomeKitShipped INSTANCE = new EndEventWelcomeKitShipped();

      private EndEventWelcomeKitShipped() {
        super(new ElementId(ELEMENT_ID), BpmnElementType.END_EVENT, "Welcome kit shipped");
      }

      @Override
      public BpmnEventType getEventType() {
        return BpmnEventType.NONE;
      }
    }

    public static final class GatewayStart extends AbstractFlowNode implements HasSuccessors<GatewayStart.Next> {
      public static final String ELEMENT_ID = "gateway_start";

      public static final GatewayStart INSTANCE = new GatewayStart();

      private GatewayStart() {
        super(new ElementId(ELEMENT_ID), BpmnElementType.EXCLUSIVE_GATEWAY);
      }

      @Override
      public Next getNext() {
        return new Next();
      }

      public static final class Next {
        public SequenceFlows<ServiceTaskShipWelcomeKit> serviceTaskShipWelcomeKit() {
          return SequenceFlows.single(new ElementId("Flow_startToShip"), ServiceTaskShipWelcomeKit.INSTANCE);
        }
      }
    }

    public static final class ServiceTaskShipWelcomeKit extends AbstractFlowNode implements HasSuccessors<ServiceTaskShipWelcomeKit.Next>, HasJobType {
      public static final String ELEMENT_ID = "serviceTask_shipWelcomeKit";

      public static final ServiceTaskShipWelcomeKit INSTANCE = new ServiceTaskShipWelcomeKit();

      private ServiceTaskShipWelcomeKit() {
        super(new ElementId(ELEMENT_ID), BpmnElementType.SERVICE_TASK, "Ship welcome kit");
      }

      @Override
      public String getJobType() {
        return ServiceTasks.SHIP_WELCOME_KIT;
      }

      @Override
      public Next getNext() {
        return new Next();
      }

      public static final class Next {
        public SequenceFlows<EndEventWelcomeKitShipped> endEventWelcomeKitShipped() {
          return SequenceFlows.single(new ElementId("Flow_shipToEnd"), EndEventWelcomeKitShipped.INSTANCE);
        }
      }
    }

    public static final class StartEventManualStart extends AbstractFlowNode implements HasSuccessors<StartEventManualStart.Next>, Event {
      public static final String ELEMENT_ID = "startEvent_manualStart";

      public static final StartEventManualStart INSTANCE = new StartEventManualStart();

      private StartEventManualStart() {
        super(new ElementId(ELEMENT_ID), BpmnElementType.START_EVENT, "Manual start (testing / fallback)");
      }

      @Override
      public BpmnEventType getEventType() {
        return BpmnEventType.NONE;
      }

      @Override
      public Next getNext() {
        return new Next();
      }

      public static final class Next {
        public SequenceFlows<GatewayStart> gatewayStart() {
          return SequenceFlows.single(new ElementId("Flow_manualToStart"), GatewayStart.INSTANCE);
        }
      }
    }

    public static final class StartEventMemberActivated extends AbstractFlowNode implements HasSuccessors<StartEventMemberActivated.Next>, Event, SignalEvent {
      public static final String ELEMENT_ID = "startEvent_memberActivated";

      public static final StartEventMemberActivated INSTANCE = new StartEventMemberActivated();

      private StartEventMemberActivated() {
        super(new ElementId(ELEMENT_ID), BpmnElementType.START_EVENT, "New member activated");
      }

      @Override
      public BpmnEventType getEventType() {
        return BpmnEventType.SIGNAL;
      }

      @Override
      public SignalName getSignal() {
        return Signals.MEMBER_ACTIVATED;
      }

      @Override
      public Next getNext() {
        return new Next();
      }

      public static final class Next {
        public SequenceFlows<GatewayStart> gatewayStart() {
          return SequenceFlows.single(new ElementId("Flow_signalToStart"), GatewayStart.INSTANCE);
        }
      }
    }
  }
}
