// Generated by bpmn-to-code
package io.miragon.training.adapter.process;

import java.util.List;

/**
 * Job worker task types used in {@code @JobWorker(type = ServiceTasks.X)} annotations.
 * Kept as {@code public static final String} because annotation arguments must be compile-time constants.
 */
public final class ServiceTasks {
  public static final String SHIP_WELCOME_KIT = "shipWelcomeKit";

  private ServiceTasks() {
  }

  public static List<String> all() {
    return List.of(
        SHIP_WELCOME_KIT);
  }
}
